Repository kimdavid0521/Vue_solo_leveling, pull requests merged in 2025-04, with the labels that each got.

#2 깃허브 커밋 템플릿 작성
  .DS_Store
  .gitmessage.txt
Labels: Feat

#9 Feat#6 login page layout
  bank-poke/db.json
  bank-poke/src/App.vue
  bank-poke/src/components/ForgotPassword.vue
  bank-poke/src/components/SignUp.vue
  bank-poke/src/pages/Analyze.vue
  bank-poke/src/pages/Asset.vue
  bank-poke/src/pages/Login.vue
  bank-poke/src/pages/Mypage.vue
  bank-poke/src/pages/NotFound.vue
  bank-poke/src/pages/Settings.vue
  bank-poke/src/pages/TransactionList.vue
  bank-poke/src/router/index.js
  bank-poke/vite.config.js
  src/components/ForgotPassword.vue
  src/components/SignUp.vue
Labels: Feat

#12 Feat#10 alarm
  bank-poke/db.json
  bank-poke/src/components/Alarm.vue
  bank-poke/src/components/MyAccount.vue
  bank-poke/src/components/SignUp.vue
  bank-poke/src/components/TimeOut.vue
  bank-poke/src/main.js
  bank-poke/src/pages/Login.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/stores/auth.js
  src/components/ForgotPassword.vue
  src/components/SignUp.vue
Labels: Feat

#11 Feat#7 transaction list page layout
  bank-poke/src/components/TableLayout.vue
  bank-poke/src/pages/TransactionList.vue
Labels: Feat

#14 Feat#5 메인 페이지 (메인 켈린더 기능, 거래 내역 추가 기능, api 연결)
  .DS_Store
  bank-poke/db.json
  bank-poke/package-lock.json
  bank-poke/package.json
  bank-poke/src/components/AddExpenseModal.vue
  bank-poke/src/components/Calender.vue
  bank-poke/src/components/Header.vue
  bank-poke/src/main.js
  bank-poke/src/pages/Login.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/NotFound.vue
  bank-poke/src/pages/TransactionList.vue
  bank-poke/src/router/index.js
  bank-poke/src/stores/counter.js
  bank-poke/vite.config.js
Labels: Feat

#17 Feat#13 mypage
  bank-poke/db.json
  bank-poke/src/components/CancleAccountModal.vue
  bank-poke/src/components/ProPaymentModal.vue
  bank-poke/src/main.js
  bank-poke/src/pages/Budget.vue
  bank-poke/src/pages/CancleAccount.vue
  bank-poke/src/pages/EditProfile.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/Mypage.vue
  bank-poke/src/pages/Premium.vue
  bank-poke/src/pages/Settings.vue
  bank-poke/src/router/index.js
Labels: Feat

#19 Feat#16 main calender api 연동 및 css 수정
  .DS_Store
  bank-poke/db.json
  bank-poke/package-lock.json
  bank-poke/package.json
  bank-poke/src/App.vue
  bank-poke/src/components/Calender.vue
  bank-poke/src/components/TableLayout.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/TransactionList.vue
Labels: Feat

#21 Feat#13 mypage
  bank-poke/db.json
  bank-poke/index.html
  bank-poke/package-lock.json
  bank-poke/src/App.vue
  bank-poke/src/assets/bankPoke.png
  bank-poke/src/assets/bankPoke1.png
  bank-poke/src/components/Alarm.vue
  bank-poke/src/components/CancleAccountModal.vue
  bank-poke/src/components/ForgotPassword.vue
  bank-poke/src/components/Header.vue
  bank-poke/src/components/LoginForm.vue
  bank-poke/src/components/MyAccount.vue
  bank-poke/src/components/SignUp.vue
  bank-poke/src/components/TimeOut.vue
  bank-poke/src/main.js
  bank-poke/src/pages/Budget.vue
  bank-poke/src/pages/EditProfile.vue
  bank-poke/src/pages/Login.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/Mypage.vue
  bank-poke/src/pages/MypageSub/Budget.vue
  bank-poke/src/pages/MypageSub/CancleAccount.vue
  bank-poke/src/pages/MypageSub/EditProfile.vue
  bank-poke/src/pages/MypageSub/ExpenseCategory.vue
  bank-poke/src/pages/MypageSub/IncomeCategory.vue
  bank-poke/src/pages/MypageSub/Premium.vue
  bank-poke/src/pages/TransactionList.vue
  bank-poke/src/router/index.js
  bank-poke/src/stores/auth.js
Labels: Feat

#23 Feat#18 analyze page layout
  bank-poke/src/components/AddAsset.vue
  bank-poke/src/components/BudgetProgress.vue
  bank-poke/src/components/CategoryExpenseChart.vue
  bank-poke/src/components/CategoryIncomeChart.vue
  bank-poke/src/components/DailyExpenseChart.vue
  bank-poke/src/components/MinusAsset.vue
  bank-poke/src/components/RetrieveAsset.vue
  bank-poke/src/components/UpdateAsset.vue
  bank-poke/src/pages/Analyze.vue
  bank-poke/src/pages/Asset.vue
  bank-poke/src/stores/assetStore.js
  bank-poke/src/stores/chartStore.js
Labels: Feat

#26 [Feat] 메인 켈린더 고정지출 기능 추가
  .DS_Store
  bank-poke/db.json
  bank-poke/src/components/AddExpenseModal.vue
  bank-poke/src/components/Calender.vue
  bank-poke/src/pages/Main.vue
Labels: Feat

#29 [Feat] 로그인 유저 정보 연동 (#7)
  bank-poke/src/components/SearchBox.vue
  bank-poke/src/pages/TransactionList.vue
Labels: Feat

#32 Feat#22 mypage2
  bank-poke/db.json
  bank-poke/src/components/AddExpenseModal.vue
  bank-poke/src/components/Alarm.vue
  bank-poke/src/components/Calender.vue
  bank-poke/src/components/SignUp.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/Mypage.vue
  bank-poke/src/pages/MypageSub/Budget.vue
  bank-poke/src/pages/MypageSub/CancleAccount.vue
  bank-poke/src/pages/MypageSub/EditProfile.vue
  bank-poke/src/pages/MypageSub/ExpenseCategory.vue
  bank-poke/src/pages/MypageSub/FixedExpense.vue
  bank-poke/src/pages/MypageSub/IncomeCategory.vue
  bank-poke/src/router/index.js
Labels: Feat

#35 Feat#28 pinia calender 연동 기능 및 수정, 삭제 기능 추가, css 수정
  .DS_Store
  bank-poke/db.json
  bank-poke/src/components/AddExpenseModal.vue
  bank-poke/src/components/Calender.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/TransactionList.vue
Labels: Feat

#36 Feat#22 repair
  README.md
  bank-poke/db.json
  bank-poke/src/assets/main.css
  bank-poke/src/assets/user-2935527_1280.png
  bank-poke/src/components/AddExpenseModal.vue
  bank-poke/src/components/Alarm.vue
  bank-poke/src/components/Header.vue
  bank-poke/src/components/SignUp.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/MypageSub/Budget.vue
  bank-poke/src/pages/MypageSub/Premium.vue
Labels: bug

#38 [Feat] 오류 수정 및 분석 페이지 기능 추가 (#18)
  bank-poke/src/components/AddAsset.vue
  bank-poke/src/components/BudgetProgress.vue
  bank-poke/src/components/CategoryExpenseChart.vue
  bank-poke/src/components/CategoryIncomeChart.vue
  bank-poke/src/components/DailyExpenseChart.vue
  bank-poke/src/components/MinusAsset.vue
  bank-poke/src/components/RetrieveAsset.vue
  bank-poke/src/components/UpdateAsset.vue
  bank-poke/src/pages/Asset.vue
  bank-poke/src/stores/chartStore.js
Labels: bug, Feat

#40 [Feat] 필터 검색 기능 구현 - 분류 (#25)
  bank-poke/src/components/SearchBox.vue
  bank-poke/src/pages/TransactionList.vue
Labels: Feat

#42 Feat#37 고정지출 삭제 및 수정시 전체 트랜잭션 수정 및 삭제 반영
  .DS_Store
  bank-poke/db.json
  bank-poke/src/components/Calender.vue
  bank-poke/src/pages/Main.vue
Labels: Feat

#44 [Feat] 메인 켈린더 디자인, 상세내역 디자인 수정
  .DS_Store
  bank-poke/db.json
  bank-poke/src/assets/background_img.png
  bank-poke/src/components/Calender.vue
  bank-poke/src/pages/Login.vue
Labels: Feat

#45 Feat#39 premium 프리미엄 기능 수정 마이프로필 css
  bank-poke/db.json
  bank-poke/src/components/AddExpenseModal.vue
  bank-poke/src/components/Header.vue
  bank-poke/src/components/MyAccount.vue
  bank-poke/src/pages/Mypage.vue
  bank-poke/src/pages/MypageSub/EditProfile.vue
  bank-poke/src/pages/MypageSub/Premium.vue
  bank-poke/src/stores/auth.js
  git
Labels: bug, Refactor

#49 json-server 배포 연결 및 최종 배포안
  .DS_Store
  bank-poke/db.json
  bank-poke/src/components/AddExpenseModal.vue
  bank-poke/src/components/Calender.vue
  bank-poke/src/components/CategoryExpenseChart.vue
  bank-poke/src/components/CategoryIncomeChart.vue
  bank-poke/src/components/DailyExpenseChart.vue
  bank-poke/src/components/Header.vue
  bank-poke/src/components/MyAccount.vue
  bank-poke/src/components/RetrieveAsset.vue
  bank-poke/src/pages/Main.vue
  bank-poke/src/pages/Mypage.vue
  bank-poke/src/pages/MypageSub/EditProfile.vue
  bank-poke/src/pages/MypageSub/FixedExpense.vue
  bank-poke/src/pages/MypageSub/Premium.vue
  bank-poke/src/pages/TransactionList.vue
  bank-poke/src/stores/auth.js
  bank-poke/vercel.json
  bank-poke/vite.config.js
  git
Labels: Feat

#51 [Refactor] 프리미엄 구독시 유저 정보 리프레시 로직 구현
  .DS_Store
  bank-poke/src/pages/MypageSub/Premium.vue
Labels: Feat

#52 [Feat] 트랜잭션 리스트
  .DS_Store
  bank-poke/src/pages/TransactionList.vue
Labels: Feat
